require:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - vendor/**/*
    - node_modules/**/*
    - lib/tasks/*
  NewCops: enable

Style/Documentation:
  Enabled: false