require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - vendor/**/*
    - node_modules/**/*
    - lib/tasks/*
  NewCops: enable
  TargetRubyVersion: 3.2.2

Rails/I18nLocaleTexts:
  Enabled: false

Style/Documentation:
  Enabled: false